spring:
  data:
    elasticsearch:
      host: localhost
    mongodb:
      username: root
      password: example
      host: localhost
      port: 27017
      database: books
      authentication-database: admin

logging:
  level:
    org:
      elasticsearch: DEBUG
      elasticsearch.transport: TRACE
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: TRACE